### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by TheRedSpy15** [xedtech/ceriumav#4]
I'm on Ubuntu 18.04 and tried running but got this error:
```

Traceback (most recent call last):
  File "av.py", line 1, in <module>
    import avcore.cli
  File "/home/hunter/ceriumav/avcore/cli.py", line 4, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'
```

**Comment by bauripalash** [comment]
Run `pip install colorama`
